version: '3'

tasks:
  setup:
    desc: "Install dependencies"
    cmds:
      - pnpm install

  dev:
    desc: "Run on localhost:3000"
    cmds:
      - pnpm dev

  build:
    desc: "Build static files"
    cmds:
      - pnpm build
